checkpoint: "../training/training-output/checkpoint/db6e7078-7b2e-48cb-b3d7-57892d093c97/inference-last.ckpt"

lead_time: 240 # hours

date: 1995-01-01T03

input:
  dataset: "../create_data/validation.zarr"

output:
  netcdf: "forecast.nc"
