# This is a basic workflow that is manually triggered

name: Eagle Pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called submit_grids.
  Submit_Grids:
    # The type of runner that the job will run on
    runs-on: ursa

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout a specific branch
      uses: actions/checkout@v4 
      with:
        ref: kb-pipeline
    - name: Submit Initial Grids
      run: |
        cd nested_eagle/scientific_workflow/data
        echo "did the grids" 
      #  JOB_ID=$(sbatch submit_grids.sh | awk '{print $4}')
      #      echo "Submitted Slurm job with ID: $JOB_ID"
            
      #      while squeue -j $JOB_ID &>/dev/null; do
      #        echo "Slurm job $JOB_ID is still running or pending. Waiting..."
      #        sleep 30 # Wait for 30 seconds before checking again
      #      done
            
      #      echo "Slurm job $JOB_ID has completed."
  Generate_Forecasts:
    # The type of runner that the job will run on
    runs-on: ursa
    steps:
      - uses: qoomon/actions--parallel-steps@v1
        id: parallel-steps
        with:
          # defaults: # see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaults
          steps: |
            - run: srun -A epic -N 1 date && sleep 20
            - run: srun -A epic -N 1 date && sleep 10

    
