# This is a basic workflow that is manually triggered

name: Nested Eagle Pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called submit_grids.
  Submit_Grids:
    # The type of runner that the job will run on
    runs-on: ursa

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout a specific branch
      uses: actions/checkout@v4 
      with:
        ref: kb-pipeline
    - name: Submit Initial Grids
      run: |
        cd nested_eagle/scientific_workflow/data

        JOB_ID=$(sbatch submit_grids.sh | awk '{print $4}')
            echo "Submitted Slurm job with ID: $JOB_ID"
            
            while squeue -j $JOB_ID &>/dev/null; do
              echo "Slurm job $JOB_ID is still running or pending. Waiting..."
              sleep 30 # Wait for 30 seconds before checking again
            done
            
            echo "Slurm job $JOB_ID to generate the grids has completed."
  Generate_GFS_Forecast:
    # The type of runner that the job will run on
    runs-on: ursa
    needs: Submit_Grids
    steps:
      - name: Generate GFS Forecast
        run: |
         cd nested_eagle/scientific_workflow/data
         
         JOB_ID=$(sbatch submit_gfs.sh | awk '{print $4}')
            echo "Submitted Slurm job with ID: $JOB_ID"
            
            while squeue -j $JOB_ID &>/dev/null; do
              echo "Slurm job $JOB_ID is still running or pending. Waiting..."
              sleep 30 # Wait for 30 seconds before checking again
            done
            
            echo "Slurm job $JOB_ID to generate the GFS forecast has completed."
  Generate_HRRR_Forecast:
    # The type of runner that the job will run on
    runs-on: ursa
    needs: Submit_Grids
    steps:
      - name: Generate HRRR Forecast
        run: |
         cd nested_eagle/scientific_workflow/data
         
         JOB_ID=$(sbatch submit_hrrr.sh | awk '{print $4}')
            echo "Submitted Slurm job with ID: $JOB_ID"
            
            while squeue -j $JOB_ID &>/dev/null; do
              echo "Slurm job $JOB_ID is still running or pending. Waiting..."
              sleep 30 # Wait for 30 seconds before checking again
            done
            
            echo "Slurm job $JOB_ID to generate the HRRR forecast has completed."
