# This is a basic workflow that is manually triggered

name: Eagle Pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Submit_Grids:
    # The type of runner that the job will run on
    runs-on: ursa

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout a specific branch
      uses: actions/checkout@v4 
      with:
        ref: kb-pipeline
    - name: Submit Initial Grids
      run: |
        cd nested_eagle/scientific_workflow/data
        sbatch submit_grids.sh
